name: run-scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'  # 毎日日本時間5:00AM（UTC 20:00）に実行

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Python をセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 必要なライブラリをインストール
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libxi6 libnss3 libxss1 libatk-bridge2.0-0 libgtk-3-0 libxrandr2
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome*.deb || sudo apt -f install -y

          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          CHROME_MAJOR_VERSION=${CHROME_VERSION%%.*}
          echo "Chrome version: $CHROME_VERSION"

          wget -O chromedriver.zip https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${CHROME_VERSION}/linux64/chromedriver-linux64.zip
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: 必要なPythonパッケージをインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: GCP認証キーを生成
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > service_account.json

      - name: スクレイピングスクリプトを実行
        run: python scrape_news_to_drive.py

      - name: 生成ファイルをアップロード
        uses: actions/upload-artifact@v4
        with:
          name: yahoo-news-${{ github.run_id }}
          path: "*.xlsx"
